import Testing
@testable import ClipMateCore

/// Literal pins. Maccy shipped Concealed/Transient SWAPPED for ~a year
/// (92d5c3d) — the convention silently defeated while the code read fine.
/// These fail the moment anyone "tidies" a string.
@Suite("PasteboardMarkers")
struct PasteboardMarkersTests {

    @Test("the org.nspasteboard strings are exactly the convention's")
    func conventionStringsArePinned() {
        #expect(PasteboardMarkers.concealed == "org.nspasteboard.ConcealedType")
        #expect(PasteboardMarkers.transient == "org.nspasteboard.TransientType")
        #expect(PasteboardMarkers.autoGenerated == "org.nspasteboard.AutoGeneratedType")
        #expect(PasteboardMarkers.ownership == "com.clipmateclone.ours")
    }

    @Test("the vendor sensitive types match what those apps actually write")
    func vendorStringsArePinned() {
        #expect(PasteboardMarkers.vendorSensitive == [
            "Pasteboard generator type",
            "com.agilebits.onepassword",
            "com.typeit4me.clipping",
            "de.petermaurer.TransientPasteboardType",
            "net.antelle.keeweb",
        ])
    }

    @Test("the Universal Clipboard marker is pinned and does NOT suppress reads")
    func remoteClipboardMarker() {
        #expect(PasteboardMarkers.remoteClipboard == "com.apple.is-remote-clipboard")
        #expect(!PasteboardMarkers.allSkipped.contains(PasteboardMarkers.remoteClipboard))
    }

    @Test("every skip marker is in the before-any-read set; ownership is NOT")
    func skipSetComposition() {
        for marker in [PasteboardMarkers.concealed, PasteboardMarkers.transient,
                       PasteboardMarkers.autoGenerated] + PasteboardMarkers.vendorSensitive {
            #expect(PasteboardMarkers.allSkipped.contains(marker))
        }
        #expect(!PasteboardMarkers.allSkipped.contains(PasteboardMarkers.ownership))
    }
}
