import Foundation

/// A read of the pasteboard at one instant.
public struct PasteboardSnapshot: Sendable {
    public var changeCount: Int
    /// UTI identifiers present, in the pasteboard's own preference order.
    public var types: [String]
    /// Bytes per type. Reading these is what forces lazy/promised data to
    /// materialize.
    public var payloads: [String: Data]

    public init(changeCount: Int, types: [String], payloads: [String: Data]) {
        self.changeCount = changeCount
        self.types = types
        self.payloads = payloads
    }
}

/// The test seam. CaptureEngine talks to this, never to NSPasteboard, so the
/// whole capture pipeline is testable with no real clipboard (spec §10).
public protocol PasteboardReading: Sendable {
    var changeCount: Int { get }
    func snapshot() -> PasteboardSnapshot?
}

public enum PasteboardMarkers {
    /// Our own private type. PasteService stamps it; CaptureEngine ignores
    /// anything carrying it. Without this, pasting re-captures the paste and
    /// the history eats itself (spec §4).
    public static let ownership = "com.clipmateclone.ours"

    /// The nspasteboard.org convention. Password managers (1Password,
    /// Bitwarden, Keychain) mark items with these. Checked BEFORE reading any
    /// data (spec §6).
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let transient = "org.nspasteboard.TransientType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"

    /// Universal Clipboard (Handoff). NOT a skip marker: the inline text/image
    /// bytes are real content. Only the fileURL rep is poison — it points at a
    /// temp file macOS deletes shortly after (Maccy G4).
    public static let remoteClipboard = "com.apple.is-remote-clipboard"

    /// Vendor-specific sensitive/transient types, accumulated by Maccy over
    /// 8 years of user reports — password managers and text expanders that
    /// predate (or ignore) the org.nspasteboard convention. Same handling as
    /// concealed: checked BEFORE reading any data.
    public static let vendorSensitive = [
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb",
    ]

    public static let allSkipped = [concealed, transient, autoGenerated] + vendorSensitive
}

public enum SupportedTypes {
    public static let plainText = "public.utf8-plain-text"
    public static let png = "public.png"
    public static let tiff = "public.tiff"
    public static let jpeg = "public.jpeg"
    /// A reference to files on disk. The payload is FileClip's newline-joined
    /// resolved URLs, NOT raw NSPasteboard bytes — see FileClip and
    /// SystemPasteboard.snapshot().
    public static let fileURL = "public.file-url"
    /// Rich formats. Stored and relayed on paste at full fidelity; the preview
    /// renders them as PLAIN TEXT only (security floor — no web engine).
    public static let rtf = "public.rtf"
    public static let html = "public.html"
    /// The web URL a copy came from. Captured as clip METADATA (Clip.sourceURL),
    /// deliberately NOT in `all` — it is not a representation, so it neither
    /// dedupes nor pastes.
    public static let sourceURL = "public.url"

    public static let images = [png, tiff, jpeg]
    /// Types stored as representations and written back on paste.
    public static let all = [plainText, fileURL, rtf, html] + images
}
